[package]
name = "rbe-ftp"
version = "0.1.0"
authors = ["Flaviu Toader <flaviu.toader@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "*"
time = "*"
